project:
  type: website
  output-dir: docs

website:
  page-footer: "Site content created for PSTAT197B-C Winter/Spring 2025 by Trevor Ruiz, updated by Anthony Coburn using Quarto; hex logo by Priscilla Siow."
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197bc"
  sidebar:
    title: "Data Science Capstone"
    style: "docked"
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - about/syllabus.qmd
      - about/schedule.qmd
      - class-meetings.qmd
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

